linters:
  enable:
  - bodyclose
  - deadcode
  - dogsled
  - dupl
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - gci
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - godot
  - godox
  - gofmt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - ireturn
  - lll
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilnil
  - nolintlint
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - staticcheck
  - structcheck
  - stylecheck
  - tenv
  - testpackage
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
  - whitespace
  - wrapcheck
  - wsl
